feat: added test file for adjust_brightness
UBC-MDS/Pythoshop pull request #39
Opened 2024-01-16 07:16 UTC by Rachel0619

Created the test file for adjust_brightness, mainly covered the following aspects:
1. Does the Image becoming brighter/darker  as expected after adjustment?
2. Does the input type of brightness_factor valid or not? they should be only int or float

Will add more tests later.

2024-01-16 19:09 UTC, jlee2843 reviewed
LGTM! I have one question: I'm seeing that there's been a lot of changes in `CHANGLOG.md`, did we create the Quarto file or was it autocreated in the process somehow?

2024-01-18 06:18 UTC, Rachel0619 commented
I see. I think this CHANGELOG.html is somehow automatically generated and the CHANGELOG.md is the one we manually maintained. TBH I also have no idea how is this html file working😭

2024-01-18 06:49 UTC, salva-u commented
In that case, perhaps we stop the manual updates?

2024-01-18 06:59 UTC, salva-u requested changes

2024-01-18 06:59 UTC, salva-u commented on tests/test_img_1_brightened.png
can you delete test images, I have created a temp dir and then remove the test image files after running the tests. Or in your case after running the tests, could you discard the "changed" image file

2024-01-18 06:59 UTC, salva-u commented on tests/test_img_1_brightness_changed.png
also discard this after test?

2024-01-18 06:59 UTC, salva-u commented on src/pythoshop/adjust_brightness.py
> +        If the image file cannot be opened or saved.
add the ValueError that checks if brightness factor is an integer or float

2024-01-18 06:59 UTC, salva-u commented on src/pythoshop/adjust_brightness.py
> +    except Exception as e:
update the docs to include this

2024-01-18 06:59 UTC, salva-u commented on src/pythoshop/adjust_brightness.py
> +        img = mpimg.imread(image_path)
add an FileNotFoundError check?

2024-01-18 06:59 UTC, salva-u commented on CHANGELOG.html
I double checked with my PR, you maybe ran an additional command, because we should not have any bootstrap, build folders, is this because of the example.ipynb file?
if not maybe we should discard these changes before merging

2024-01-18 06:59 UTC, salva-u commented
I cannot run the test using $ python -m unittest

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK

2024-01-18 17:40 UTC, Rachel0619 commented
> I cannot run the test using $ python -m unittest
> 
> Ran 0 tests in 0.000s
> 
> OK

I think we might want to use $ pytest tests/ in our package

2024-01-18 17:42 UTC, Rachel0619 commented
> In that case, perhaps we stop the manual updates?

Or we can delete the CHANGELOG.html which is generated automatically by accident.

2024-01-18 21:40 UTC, closed without merging

2024-01-18 21:40 UTC, jlee2843 commented
More changes are needed, follow the comments above.