42 test resize image function
UBC-MDS/Pythoshop pull request #43
Opened 2024-01-18 06:41 UTC by salva-u

Please keep in mind the function was renamed to resize_image
also I added another option to adjust image size, by adding borders& resize

Name                                                                                 Stmts   Miss  Cover   Missing
------------------------------------------------------------------------------------------------------------------
C:\Users\salva\Desktop\ubc_mds_24\524_lab1\Pythoshop\src\pythoshop\__init__.py           2      0   100%
C:\Users\salva\Desktop\ubc_mds_24\524_lab1\Pythoshop\src\pythoshop\resize_image.py      36      7    81%   40, 69-75
test_resize_image.py                                                                    48      1    98%   78
------------------------------------------------------------------------------------------------------------------
TOTAL                                                                                   86      8    91%

2024-01-18 22:58 UTC, Rachel0619 approved these changes
LGTM!

2024-01-19 07:28 UTC, ella-irene requested changes
Just one small change in the docstrings but otherwise everything looks good to me! Great work.

2024-01-19 07:28 UTC, ella-irene commented on src/pythoshop/resize_image.py
> +    - IOError: If the image file cannot be opened or saved.
I think you can delete this line about raising an IOError since you raise a FileNotFoundError in your function instead.

2024-01-19 20:38 UTC, jlee2843 approved these changes
LGTM! Just watch out for the conflicts!

2024-01-19 20:52 UTC, merged